//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerLoyaltyManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class managementsystem_dbEntities : DbContext
    {
        public managementsystem_dbEntities()
            : base("name=managementsystem_dbEntities")
        {
        }

        //private static string GetConnectionString()
        //{
        //    // Retrieve the connection string from environment variables
        //    string envConnectionString = Environment.GetEnvironmentVariable("ENV_CONNECTION_STRING");

        //    // If the environment variable is not set, use a fallback connection string
        //    if (string.IsNullOrEmpty(envConnectionString))
        //    {
        //        // Fallback to a direct connection string (for testing purposes)
        //        return "data source=managementsystem-team04.database.windows.net;initial catalog=managementsystem_db;persist security info=True;user id=adminDb;password=5uK]Fd£C29_E;MultipleActiveResultSets=True;App=EntityFramework";
        //    }

        //    return envConnectionString;
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<LoyaltyProgram> LoyaltyPrograms { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TransactionLoyalty> TransactionLoyalties { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
